import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DATABASE_PATH = os.path.join(BASE_DIR, 'data', 'cxo_finder.db')

SECRET_KEY = 'cxo-finder-secret-2024'

# 100 Real-world CXO Names database
CXO_DATABASE = [
    {"name": "Satya Nadella", "title": "CEO", "company": "Microsoft", "linkedin": "https://linkedin.com/in/satyanadella"},
    {"name": "Tim Cook", "title": "CEO", "company": "Apple", "linkedin": "https://linkedin.com/in/tim-cook"},
    {"name": "Sundar Pichai", "title": "CEO", "company": "Google", "linkedin": "https://linkedin.com/in/sundarpichai"},
    {"name": "Andy Jassy", "title": "CEO", "company": "Amazon", "linkedin": "https://linkedin.com/in/andy-jassy"},
    {"name": "Mark Zuckerberg", "title": "CEO", "company": "Meta", "linkedin": "https://linkedin.com/in/mark-zuckerberg"},
    {"name": "Elon Musk", "title": "CEO", "company": "Tesla", "linkedin": "https://linkedin.com/in/elonmusk"},
    {"name": "Jensen Huang", "title": "CEO", "company": "NVIDIA", "linkedin": "https://linkedin.com/in/jensen-huang"},
    {"name": "Lisa Su", "title": "CEO", "company": "AMD", "linkedin": "https://linkedin.com/in/lisa-su"},
    {"name": "Pat Gelsinger", "title": "CEO", "company": "Intel", "linkedin": "https://linkedin.com/in/patgelsinger"},
    {"name": "Arvind Krishna", "title": "CEO", "company": "IBM", "linkedin": "https://linkedin.com/in/arvindkrishna"},
    {"name": "Chuck Robbins", "title": "CEO", "company": "Cisco", "linkedin": "https://linkedin.com/in/chuckrobbins"},
    {"name": "Hock Tan", "title": "CEO", "company": "Broadcom", "linkedin": "https://linkedin.com/in/hock-tan"},
    {"name": "Bob Swan", "title": "CFO", "company": "Intel", "linkedin": "https://linkedin.com/in/bobswan"},
    {"name": "Amy Hood", "title": "CFO", "company": "Microsoft", "linkedin": "https://linkedin.com/in/amyhood"},
    {"name": "Luca Maestri", "title": "CFO", "company": "Apple", "linkedin": "https://linkedin.com/in/lucamaestri"},
    {"name": "Ruth Porat", "title": "CFO", "company": "Google", "linkedin": "https://linkedin.com/in/ruthporat"},
    {"name": "Brian Olsavsky", "title": "CFO", "company": "Amazon", "linkedin": "https://linkedin.com/in/brianolsavsky"},
    {"name": "Dave Wehner", "title": "CFO", "company": "Meta", "linkedin": "https://linkedin.com/in/davewehner"},
    {"name": "Kathy Warden", "title": "CEO", "company": "Northrop Grumman", "linkedin": "https://linkedin.com/in/kathywarden"},
    {"name": "Mary Barra", "title": "CEO", "company": "General Motors", "linkedin": "https://linkedin.com/in/marybarra"},
    {"name": "Jim Farley", "title": "CEO", "company": "Ford", "linkedin": "https://linkedin.com/in/jimfarley"},
    {"name": "Carlos Tavares", "title": "CEO", "company": "Stellantis", "linkedin": "https://linkedin.com/in/carlos-tavares"},
    {"name": "Jamie Dimon", "title": "CEO", "company": "JPMorgan Chase", "linkedin": "https://linkedin.com/in/jamiedimon"},
    {"name": "Brian Moynihan", "title": "CEO", "company": "Bank of America", "linkedin": "https://linkedin.com/in/brianmoynihan"},
    {"name": "Jane Fraser", "title": "CEO", "company": "Citigroup", "linkedin": "https://linkedin.com/in/janefraser"},
    {"name": "Charles Scharf", "title": "CEO", "company": "Wells Fargo", "linkedin": "https://linkedin.com/in/charlesscharf"},
    {"name": "David Solomon", "title": "CEO", "company": "Goldman Sachs", "linkedin": "https://linkedin.com/in/davidsolomon"},
    {"name": "James Gorman", "title": "CEO", "company": "Morgan Stanley", "linkedin": "https://linkedin.com/in/jamesgorman"},
    {"name": "Larry Fink", "title": "CEO", "company": "BlackRock", "linkedin": "https://linkedin.com/in/larry-fink"},
    {"name": "Bob Chapek", "title": "CEO", "company": "Disney", "linkedin": "https://linkedin.com/in/bobchapek"},
    {"name": "Brian Cornell", "title": "CEO", "company": "Target", "linkedin": "https://linkedin.com/in/briancornell"},
    {"name": "Doug McMillon", "title": "CEO", "company": "Walmart", "linkedin": "https://linkedin.com/in/dougmcmillon"},
    {"name": "Rosalind Brewer", "title": "CEO", "company": "Walgreens", "linkedin": "https://linkedin.com/in/rosalindbrewer"},
    {"name": "Karen Lynch", "title": "CEO", "company": "CVS Health", "linkedin": "https://linkedin.com/in/karenlynch"},
    {"name": "Albert Bourla", "title": "CEO", "company": "Pfizer", "linkedin": "https://linkedin.com/in/albertbourla"},
    {"name": "Pascal Soriot", "title": "CEO", "company": "AstraZeneca", "linkedin": "https://linkedin.com/in/pascalsoriot"},
    {"name": "Gail Boudreaux", "title": "CEO", "company": "Anthem", "linkedin": "https://linkedin.com/in/gailboudreaux"},
    {"name": "Bruce Broussard", "title": "CEO", "company": "Humana", "linkedin": "https://linkedin.com/in/brucebroussard"},
    {"name": "David Cordani", "title": "CEO", "company": "Cigna", "linkedin": "https://linkedin.com/in/davidcordani"},
    {"name": "Shantanu Narayen", "title": "CEO", "company": "Adobe", "linkedin": "https://linkedin.com/in/shantanunarayen"},
    {"name": "Safra Catz", "title": "CEO", "company": "Oracle", "linkedin": "https://linkedin.com/in/safracatz"},
    {"name": "Bill McDermott", "title": "CEO", "company": "ServiceNow", "linkedin": "https://linkedin.com/in/billmcdermott"},
    {"name": "Frank Slootman", "title": "CEO", "company": "Snowflake", "linkedin": "https://linkedin.com/in/frankslootman"},
    {"name": "Dario Amodei", "title": "CEO", "company": "Anthropic", "linkedin": "https://linkedin.com/in/dario-amodei"},
    {"name": "Sam Altman", "title": "CEO", "company": "OpenAI", "linkedin": "https://linkedin.com/in/samaltman"},
    {"name": "Arvind Krishna", "title": "CEO", "company": "IBM", "linkedin": "https://linkedin.com/in/arvindkrishna"},
    {"name": "George Kurtz", "title": "CEO", "company": "CrowdStrike", "linkedin": "https://linkedin.com/in/georgekurtz"},
    {"name": "Nikesh Arora", "title": "CEO", "company": "Palo Alto Networks", "linkedin": "https://linkedin.com/in/nikesharora"},
    {"name": "Raghu Raghuram", "title": "CEO", "company": "VMware", "linkedin": "https://linkedin.com/in/raghuraghu"},
    {"name": "Peter McKay", "title": "CEO", "company": "Veeam", "linkedin": "https://linkedin.com/in/petermckay"},
    {"name": "Thomas Kurian", "title": "CEO", "company": "Google Cloud", "linkedin": "https://linkedin.com/in/thomaskurian"},
    {"name": "Adam Selipsky", "title": "CEO", "company": "AWS", "linkedin": "https://linkedin.com/in/adamselipsky"},
    {"name": "Abhijit Dubey", "title": "CEO", "company": "NTT Data", "linkedin": "https://linkedin.com/in/abhijitdubey"},
    {"name": "Ralf Schneider", "title": "CTO", "company": "Allianz", "linkedin": "https://linkedin.com/in/ralfschneider"},
    {"name": "Werner Vogels", "title": "CTO", "company": "Amazon", "linkedin": "https://linkedin.com/in/wernervogels"},
    {"name": "Kevin Scott", "title": "CTO", "company": "Microsoft", "linkedin": "https://linkedin.com/in/kevinscott"},
    {"name": "Mike Schroepfer", "title": "CTO", "company": "Meta", "linkedin": "https://linkedin.com/in/mikeschroepfer"},
    {"name": "Greg Lavender", "title": "CTO", "company": "Intel", "linkedin": "https://linkedin.com/in/greglavender"},
    {"name": "Faisal Masud", "title": "CTO", "company": "Staples", "linkedin": "https://linkedin.com/in/faisalmasud"},
    {"name": "Rao Cherukuri", "title": "CTO", "company": "Intellicheck", "linkedin": "https://linkedin.com/in/raocherukuri"},
    {"name": "Lori Beer", "title": "CIO", "company": "JPMorgan Chase", "linkedin": "https://linkedin.com/in/loribeer"},
    {"name": "Cathy Bessant", "title": "CTO", "company": "Bank of America", "linkedin": "https://linkedin.com/in/cathybessant"},
    {"name": "Gary Bhattacharjee", "title": "CIO", "company": "MetLife", "linkedin": "https://linkedin.com/in/garybhattacharjee"},
    {"name": "Bret Taylor", "title": "CTO", "company": "Salesforce", "linkedin": "https://linkedin.com/in/brettaylor"},
    {"name": "Marc Benioff", "title": "CEO", "company": "Salesforce", "linkedin": "https://linkedin.com/in/marcbenioff"},
    {"name": "Parker Harris", "title": "CTO", "company": "Salesforce", "linkedin": "https://linkedin.com/in/parkerharris"},
    {"name": "Dheeraj Pandey", "title": "CEO", "company": "Nutanix", "linkedin": "https://linkedin.com/in/dheerajpandey"},
    {"name": "Jayshree Ullal", "title": "CEO", "company": "Arista Networks", "linkedin": "https://linkedin.com/in/jayshreeullal"},
    {"name": "Victor Dodig", "title": "CEO", "company": "CIBC", "linkedin": "https://linkedin.com/in/victordodig"},
    {"name": "Urs Holzle", "title": "CTO", "company": "Google Infrastructure", "linkedin": "https://linkedin.com/in/ursholzle"},
    {"name": "Diane Greene", "title": "CEO", "company": "Google Cloud", "linkedin": "https://linkedin.com/in/dianegreene"},
    {"name": "John Chambers", "title": "CEO", "company": "JC2 Ventures", "linkedin": "https://linkedin.com/in/johnchambers"},
    {"name": "Steve Mollenkopf", "title": "CEO", "company": "Qualcomm", "linkedin": "https://linkedin.com/in/stevemollenkopf"},
    {"name": "Cristiano Amon", "title": "CEO", "company": "Qualcomm", "linkedin": "https://linkedin.com/in/cristianoamon"},
    {"name": "Jack Dorsey", "title": "CEO", "company": "Block", "linkedin": "https://linkedin.com/in/jackdorsey"},
    {"name": "Daniel Zhang", "title": "CEO", "company": "Alibaba", "linkedin": "https://linkedin.com/in/danielzhang"},
    {"name": "Pony Ma", "title": "CEO", "company": "Tencent", "linkedin": "https://linkedin.com/in/ponyma"},
    {"name": "Lei Jun", "title": "CEO", "company": "Xiaomi", "linkedin": "https://linkedin.com/in/leijun"},
    {"name": "Liu Qiangdong", "title": "CEO", "company": "JD.com", "linkedin": "https://linkedin.com/in/liuqiangdong"},
    {"name": "Ren Zhengfei", "title": "CEO", "company": "Huawei", "linkedin": "https://linkedin.com/in/renzhengfei"},
    {"name": "Indra Nooyi", "title": "CEO", "company": "PepsiCo", "linkedin": "https://linkedin.com/in/indranooyi"},
    {"name": "Ramon Laguarta", "title": "CEO", "company": "PepsiCo", "linkedin": "https://linkedin.com/in/ramonlaguarta"},
    {"name": "James Quincey", "title": "CEO", "company": "Coca-Cola", "linkedin": "https://linkedin.com/in/jamesquincey"},
    {"name": "Arne Sorenson", "title": "CEO", "company": "Marriott", "linkedin": "https://linkedin.com/in/arnesorenson"},
    {"name": "Anthony Capuano", "title": "CEO", "company": "Marriott", "linkedin": "https://linkedin.com/in/anthonycapuano"},
    {"name": "Sébastien Bazin", "title": "CEO", "company": "Accor", "linkedin": "https://linkedin.com/in/sebastienbazin"},
    {"name": "Christopher Nassetta", "title": "CEO", "company": "Hilton", "linkedin": "https://linkedin.com/in/christophernassetta"},
    {"name": "Keith Barr", "title": "CEO", "company": "IHG", "linkedin": "https://linkedin.com/in/keithbarr"},
    {"name": "Dara Khosrowshahi", "title": "CEO", "company": "Uber", "linkedin": "https://linkedin.com/in/dara-khosrowshahi"},
    {"name": "Logan Green", "title": "CEO", "company": "Lyft", "linkedin": "https://linkedin.com/in/logangreen"},
    {"name": "Brian Chesky", "title": "CEO", "company": "Airbnb", "linkedin": "https://linkedin.com/in/brianchesky"},
    {"name": "Drew Houston", "title": "CEO", "company": "Dropbox", "linkedin": "https://linkedin.com/in/drewhouston"},
    {"name": "Aaron Levie", "title": "CEO", "company": "Box", "linkedin": "https://linkedin.com/in/aaronlevie"},
    {"name": "Tobi Lutke", "title": "CEO", "company": "Shopify", "linkedin": "https://linkedin.com/in/tobiaslutke"},
    {"name": "Stewart Butterfield", "title": "CEO", "company": "Slack", "linkedin": "https://linkedin.com/in/stewart"},
    {"name": "Eric Yuan", "title": "CEO", "company": "Zoom", "linkedin": "https://linkedin.com/in/ericyuan"},
    {"name": "Peter Gassner", "title": "CEO", "company": "Veeva Systems", "linkedin": "https://linkedin.com/in/petergassner"},
    {"name": "Howie Liu", "title": "CEO", "company": "Airtable", "linkedin": "https://linkedin.com/in/howieliu"},
    {"name": "Vlad Tenev", "title": "CEO", "company": "Robinhood", "linkedin": "https://linkedin.com/in/vladtenev"},
    {"name": "Patrick Collison", "title": "CEO", "company": "Stripe", "linkedin": "https://linkedin.com/in/patrickcollison"},
]
